package com.relivus.dialect;

import com.relivus.common.exception.ErrorCode;
import com.relivus.common.exception.RelivusException;
import com.relivus.schema.model.ColumnMetadata;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * PostgreSQL 16 方言。
 *
 * <ul>
 *   <li>标识符双引号引用</li>
 *   <li>分页 {@code LIMIT size OFFSET offset}</li>
 *   <li>自增 {@code GENERATED BY DEFAULT AS IDENTITY}、布尔 {@code BOOLEAN}、
 *       时间 {@code TIMESTAMP}、二进制 {@code BYTEA}</li>
 *   <li>ENUM 独立类型（列级元数据取自 pg_type + pg_enum）</li>
 *   <li>CHECK 取自 {@code pg_constraint} + {@code pg_get_constraintdef}</li>
 * </ul>
 */
@Component
public class PostgreSQLDialect extends AbstractJdbcDialect {

    private static final Logger LOG = LoggerFactory.getLogger(PostgreSQLDialect.class);
    private static final String DEFAULT_SCHEMA = "public";

    private static final DataTypeMapping MAPPING = new DataTypeMapping(
            "BOOLEAN", "TIMESTAMP", "BYTEA", "GENERATED BY DEFAULT AS IDENTITY",
            null);

    @Override
    public String name() {
        return "postgresql";
    }

    @Override
    public boolean supports(DatabaseMetaData metaData) {
        try {
            String product = metaData.getDatabaseProductName();
            return product != null && product.toLowerCase().contains("postgresql");
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to read database product name", e);
        }
    }

    @Override
    public String buildJdbcUrl(String host, int port, String database) {
        return "jdbc:postgresql://" + host + ":" + port + "/" + database;
    }

    @Override
    String catalog(Connection connection, DatabaseMetaData metaData) {
        return null;
    }

    @Override
    String schema(Connection connection, DatabaseMetaData metaData) throws SQLException {
        String current = connection.getSchema();
        return (current == null || current.isBlank()) ? DEFAULT_SCHEMA : current;
    }

    @Override
    boolean isSystemTable(String tableName, String schema) {
        if (schema == null || !schema.equalsIgnoreCase(DEFAULT_SCHEMA)) {
            return !DEFAULT_SCHEMA.equalsIgnoreCase(schema);
        }
        return tableName.startsWith("pg_");
    }

    @Override
    boolean isAutoIncrement(ResultSet columnRs) throws SQLException {
        // 显式 IDENTITY 列由 findIdentityColumns（information_schema）识别；
        // 此处兜底 serial 序列默认值（nextval）。
        String defaultValue = columnRs.getString("COLUMN_DEF");
        return defaultValue != null && defaultValue.contains("nextval");
    }

    @Override
    Set<String> findIdentityColumns(Connection connection, String schema, String tableName) {
        Set<String> identity = new HashSet<>();
        String sql = "SELECT column_name FROM information_schema.columns "
                + "WHERE table_schema = ? AND table_name = ? AND is_identity = 'YES'";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, schema == null ? DEFAULT_SCHEMA : schema);
            ps.setString(2, tableName);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    identity.add(rs.getString("column_name"));
                }
            }
        } catch (SQLException e) {
            LOG.warn("Failed to introspect identity columns for table={}, err={}", tableName, e.getMessage());
        }
        return identity;
    }

    @Override
    Map<String, List<String>> findEnumValues(Connection connection, String schema, String tableName) {
        Map<String, List<String>> result = new LinkedHashMap<>();
        String sql = "SELECT a.attname AS column_name, e.enumlabel AS enum_value "
                + "FROM pg_attribute a "
                + "JOIN pg_type t ON t.oid = a.atttypid "
                + "LEFT JOIN pg_enum e ON e.enumtypid = t.oid "
                + "JOIN pg_class c ON c.oid = a.attrelid "
                + "JOIN pg_namespace n ON n.oid = c.relnamespace "
                + "WHERE c.relname = ? AND n.nspname = ? AND e.enumlabel IS NOT NULL "
                + "ORDER BY a.attnum, e.enumsortorder";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, tableName);
            ps.setString(2, schema == null ? DEFAULT_SCHEMA : schema);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    result.computeIfAbsent(rs.getString("column_name"), k -> new ArrayList<>())
                            .add(rs.getString("enum_value"));
                }
            }
        } catch (SQLException e) {
            LOG.warn("Failed to introspect enum values for table={}, err={}", tableName, e.getMessage());
        }
        return result;
    }

    @Override
    List<String[]> findCheckConstraints(Connection connection, String schema, String tableName) {
        List<String[]> result = new ArrayList<>();
        String sql = "SELECT c.conname, pg_get_constraintdef(c.oid) AS definition "
                + "FROM pg_constraint c "
                + "JOIN pg_class cl ON cl.oid = c.conrelid "
                + "JOIN pg_namespace n ON n.oid = cl.relnamespace "
                + "WHERE c.contype = 'c' AND cl.relname = ? AND n.nspname = ?";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, tableName);
            ps.setString(2, schema == null ? DEFAULT_SCHEMA : schema);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    result.add(new String[]{rs.getString("conname"), rs.getString("definition")});
                }
            }
        } catch (SQLException e) {
            LOG.warn("Failed to introspect check constraints for table={}, err={}", tableName, e.getMessage());
        }
        return result;
    }

    @Override
    public DataTypeMapping getTypeMapping() {
        return MAPPING;
    }

    @Override
    public PaginationSyntax getPaginationSyntax() {
        return PaginationSyntax.POSTGRESQL;
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier.replace("\"", "\"\"") + "\"";
    }

    /**
     * 覆盖 INSERT 构建：ENUM 列占位符显式加 {@code ::类型} 转换。
     * <p>PG 预编译参数默认推断为 text，与 enum 域类型比较会触发
     * {@code operator does not exist: user_gender = character varying}，
     * 因此需要声明式转换（psql 字面量可直接隐式转换，JDBC 参数不能）。
     */
    @Override
    public String buildInsertSql(String table, List<ColumnMetadata> columns) {
        if (columns == null || columns.isEmpty()) {
            throw new RelivusException(ErrorCode.VALIDATION_FAILED, "INSERT requires at least one column");
        }
        StringBuilder sb = new StringBuilder("INSERT INTO ").append(table).append(" (");
        StringBuilder values = new StringBuilder(" VALUES (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) {
                sb.append(", ");
                values.append(", ");
            }
            sb.append(quoteIdentifier(columns.get(i).columnName()));
            if (columns.get(i).isEnum()) {
                values.append("?::").append(columns.get(i).dataType());
            } else {
                values.append("?");
            }
        }
        return sb.append(")").append(values).append(")").toString();
    }
}