package com.relivus.masking;

import com.relivus.dialect.DatabaseDialect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Map;

/**
 * JOIN 一致性验证（临时快照表）。
 *
 * <p>流程：脱敏前将目标行（主键 + JOIN 键）采样到目标库临时快照表；脱敏后逐条重跑
 * JOIN SQL（按主键绑定），对比返回行数与 JOIN 键值。不采用长事务（大表回滚代价高），
 * 也不使用映射表反向还原（FixedMask 等算法不可逆）。验证结束后清理快照表。
 */
public class JoinConsistencyVerifier {

    private static final Logger LOG = LoggerFactory.getLogger(JoinConsistencyVerifier.class);

    /** 验证结果。 */
    public record JoinVerificationResult(int checkedRows, int mismatchRows, boolean consistent, String message) {

        public static JoinVerificationResult success(int checkedRows) {
            return new JoinVerificationResult(checkedRows, 0, true,
                    "JOIN 一致性验证通过，抽样 " + checkedRows + " 行全部一致");
        }

        public static JoinVerificationResult failed(int checkedRows, int mismatchRows) {
            return new JoinVerificationResult(checkedRows, mismatchRows, false,
                    "JOIN 一致性验证失败：" + mismatchRows + "/" + checkedRows + " 行不一致");
        }
    }

    /**
     * 创建快照表并写入采样行。
     *
     * @return 快照表名
     */
    public String createSnapshot(JdbcTemplate jdbc, DatabaseDialect dialect, String snapshotTable,
                                 String targetTable, String pkColumn, String joinKeyColumn, String whereClause) {
        // 幂等：先清理同名残留快照（任务重跑或上次异常中断后遗留），避免 CREATE 冲突
        jdbc.execute("DROP TABLE IF EXISTS " + dialect.quoteIdentifier(snapshotTable));
        String identity = "postgresql".equalsIgnoreCase(dialect.name())
                ? "BIGINT GENERATED BY DEFAULT AS IDENTITY"
                : "BIGINT AUTO_INCREMENT";
        jdbc.execute("CREATE TABLE " + dialect.quoteIdentifier(snapshotTable) + " ("
                + "id " + identity + " PRIMARY KEY, "
                + "pk_value BIGINT NOT NULL, "
                + "join_key VARCHAR(1024))");
        String sql = "INSERT INTO " + dialect.quoteIdentifier(snapshotTable)
                + " (pk_value, join_key) SELECT "
                + dialect.quoteIdentifier(pkColumn) + ", " + dialect.quoteIdentifier(joinKeyColumn)
                + " FROM " + dialect.quoteIdentifier(targetTable);
        if (whereClause != null && !whereClause.isBlank()) {
            sql += " WHERE " + whereClause;
        }
        jdbc.update(sql);
        return snapshotTable;
    }

    /**
     * 执行一致性校验（校验完成后删除快照表）。
     *
     * @param joinSql 带主键条件参数化的 JOIN 查询，如
     *                {@code SELECT oi.order_id FROM order o JOIN order_item oi ON o.id = oi.order_id WHERE o.id = ?}
     */
    public JoinVerificationResult verify(JdbcTemplate jdbc, DatabaseDialect dialect, String snapshotTable,
                                         String joinSql, String pkColumn, String joinKeyColumn) {
        int checked = 0;
        int mismatch = 0;
        try {
            List<Map<String, Object>> snapshots =
                    jdbc.queryForList("SELECT pk_value, join_key FROM " + dialect.quoteIdentifier(snapshotTable));
            for (Map<String, Object> snapshot : snapshots) {
                checked++;
                // 主键参数保留数据库原始类型（数值主键绑 int8 列名，避免 text 隐式转换失败）
                Object pkValue = snapshot.get("pk_value");
                String expectedJoinKey = snapshot.get("join_key") == null ? null : String.valueOf(snapshot.get("join_key"));
                List<Map<String, Object>> rows;
                try {
                    rows = jdbc.queryForList(joinSql, pkValue);
                } catch (RuntimeException e) {
                    LOG.warn("JOIN verification sql failed for pk={}: {}", pkValue, e.getMessage());
                    mismatch++;
                    continue;
                }
                if (rows.isEmpty()) {
                    // 脱敏只改列值、不改变 JOIN 行集合：脱敏前该主键在 JOIN 中本无行，视为一致
                    continue;
                }
                Object actual = rows.get(0).get(joinKeyColumn);
                String actualJoinKey = actual == null ? null : String.valueOf(actual);
                if (expectedJoinKey != null && !expectedJoinKey.equals(actualJoinKey)) {
                    mismatch++;
                }
            }
        } finally {
            dropSnapshot(jdbc, dialect, snapshotTable);
        }
        return mismatch == 0 ? JoinVerificationResult.success(checked)
                : JoinVerificationResult.failed(checked, mismatch);
    }

    /** 清理快照表（失败兜底，防止临时表残留）。 */
    public void dropSnapshot(JdbcTemplate jdbc, DatabaseDialect dialect, String snapshotTable) {
        try {
            jdbc.execute("DROP TABLE IF EXISTS " + dialect.quoteIdentifier(snapshotTable));
        } catch (RuntimeException e) {
            LOG.warn("Failed to drop join snapshot table {}: {}", snapshotTable, e.getMessage());
        }
    }
}