-- ============================================================
-- Relivus 元库初始化（PostgreSQL 方言）V1
-- 说明：目标库绝不执行本脚本；仅 Relivus 自有库（relivus_meta）使用。
-- 外键规范：FOREIGN KEY + SET NULL（配置删除时任务/日志等关联数据行为与 MySQL 保持同口径，
-- 任务日志随任务级联删除）。
-- ============================================================

-- 目标库连接（密码为 AES-GCM 密文：Base64(IV + cipherText + tag)，绝无明文）
CREATE TABLE df_connection (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(64)  NOT NULL,
    db_type         VARCHAR(16)  NOT NULL,                    -- mysql / postgresql
    host            VARCHAR(128) NOT NULL,
    port            INT          NOT NULL,
    database_name   VARCHAR(64)  NOT NULL,
    username        VARCHAR(64)  NOT NULL,
    password_cipher VARCHAR(512) NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_connection_name UNIQUE (name)
);

-- 统一任务表（生成/脱敏共用，DOC-05）
CREATE TABLE df_task (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type        VARCHAR(32) NOT NULL,                    -- GENERATION / MASKING
    connection_id    BIGINT      NULL,
    config_json      TEXT        NULL,
    status           VARCHAR(16) NOT NULL DEFAULT 'PENDING',  -- PENDING/RUNNING/SUCCESS/FAILED/CANCELLED
    progress         INT         NOT NULL DEFAULT 0,           -- 0-100
    total_rows       BIGINT      NOT NULL DEFAULT 0,
    processed_rows   BIGINT      NOT NULL DEFAULT 0,
    error_message    TEXT        NULL,
    cancel_requested BOOLEAN     NOT NULL DEFAULT FALSE,      -- 取消持久化标志（DOC-11.7）
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at       TIMESTAMP   NULL,
    finished_at      TIMESTAMP   NULL
);
CREATE INDEX idx_task_status ON df_task (status);
CREATE INDEX idx_task_created ON df_task (created_at);

-- 任务日志（DOC-05）
CREATE TABLE df_task_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT      NOT NULL,
    level      VARCHAR(16) NOT NULL,                          -- INFO/WARN/ERROR
    message    TEXT        NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_log_task FOREIGN KEY (task_id) REFERENCES df_task (id) ON DELETE CASCADE
);
CREATE INDEX idx_task_log_task_id ON df_task_log (task_id);

-- 脱敏映射表（DOC-04：同组同原始值跨表保持一致，唯一键防并发重复写）
CREATE TABLE df_mask_mapping (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    column_group  VARCHAR(255) NOT NULL,
    original_hash VARCHAR(64)  NOT NULL,                      -- SHA-256 十六进制
    masked_value  TEXT         NOT NULL,
    algorithm     VARCHAR(64)  NOT NULL,
    key_version   INT          NOT NULL DEFAULT 1,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mask_group_hash UNIQUE (column_group, original_hash)
);

-- 操作审计（DOC-10）
CREATE TABLE df_audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action     VARCHAR(64)  NOT NULL,                         -- connection_create / generation_execute 等
    target     VARCHAR(255) NULL,
    detail     TEXT         NULL,                             -- 敏感信息必须已脱敏
    result     VARCHAR(16)  NOT NULL DEFAULT 'success',
    trace_id   VARCHAR(64)  NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_action ON df_audit_log (action);
CREATE INDEX idx_audit_created ON df_audit_log (created_at);