-- ============================================================
-- Relivus 元库初始化（PostgreSQL 方言）——新增 AI 模型配置
-- 说明：api_key 以 AES-GCM 密文存储（Base64(IV + cipherText + tag)），绝无明文；
--       active 单活跃由应用层事务保证（激活前将其他配置置为 inactive）。
-- ============================================================

CREATE TABLE df_ai_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(64)  NOT NULL,
    base_url       VARCHAR(255) NOT NULL,                     -- OpenAI 兼容接口基址
    api_key_cipher VARCHAR(512) NOT NULL,                     -- AES-GCM 密文，响应不回传明文
    model          VARCHAR(64)  NOT NULL,                     -- 模型名（如 deepseek-chat / glm-4-plus）
    active         BOOLEAN      NOT NULL DEFAULT FALSE,       -- 当前激活的 AI 配置（生成任务使用）
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_config_name UNIQUE (name)
);
CREATE INDEX idx_ai_config_active ON df_ai_config (active);