package com.relivus.integration;

import com.relivus.dialect.MySQLDialect;
import com.relivus.dialect.PostgreSQLDialect;
import com.relivus.schema.JdbcSchemaIntrospector;
import com.relivus.schema.SchemaIntrospector;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.testcontainers.containers.JdbcDatabaseContainer;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 集成测试基类。
 *
 * <p>共享 MySQL 8.0 与 PostgreSQL 16 容器；Docker 不可用时整个测试类自动跳过
 * （{@code disabledWithoutDocker}，assumption 失败按 skipped 处理，不阻塞构建）。
 * 部署层无任何 Docker 依赖，仅测试容器隔离目标库。
 */
@Testcontainers(disabledWithoutDocker = true)
abstract class AbstractDatabaseIT {

    @Container
    static final MySQLContainer<?> MYSQL = new MySQLContainer<>("mysql:8.0")
            .withDatabaseName("relivus")
            .withUsername("relivus")
            .withPassword("relivus123");

    @Container
    static final PostgreSQLContainer<?> PG = new PostgreSQLContainer<>("postgres:16")
            .withDatabaseName("relivus")
            .withUsername("relivus")
            .withPassword("relivus123");

    static final MySQLDialect MYSQL_DIALECT = new MySQLDialect();
    static final PostgreSQLDialect PG_DIALECT = new PostgreSQLDialect();
    static final SchemaIntrospector INTROSPECTOR = new JdbcSchemaIntrospector();

    protected static DataSource mysqlDataSource() {
        return dataSource(MYSQL.getJdbcUrl(), MYSQL.getUsername(), MYSQL.getPassword());
    }

    protected static DataSource pgDataSource() {
        return dataSource(PG.getJdbcUrl(), PG.getUsername(), PG.getPassword());
    }

    private static DataSource dataSource(String url, String user, String pass) {
        DriverManagerDataSource ds = new DriverManagerDataSource();
        ds.setUrl(url);
        ds.setUsername(user);
        ds.setPassword(pass);
        return ds;
    }

    /** 是否 PostgreSQL 容器。 */
    protected static boolean isPg(JdbcDatabaseContainer<?> container) {
        return container instanceof PostgreSQLContainer;
    }

    /** 执行任意数量的 DDL 语句（逐条 execute）。 */
    protected static void execute(DataSource dataSource, String... sqlStatements) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            for (String sql : sqlStatements) {
                statement.execute(sql);
            }
        }
    }

    /** MySQL 风格自增主键列。 */
    protected static String autoIncrementMysql() {
        return "BIGINT NOT NULL AUTO_INCREMENT";
    }

    /** PostgreSQL 风格自增主键列。 */
    protected static String autoIncrementPg() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY";
    }
}