package com.relivus.integration;

import com.relivus.common.exception.ErrorCode;
import com.relivus.common.exception.RelivusException;
import com.relivus.dto.GenerationConfig;
import com.relivus.dto.GenerationConfig.TableConfig;
import com.relivus.generator.DataGenerationEngine;
import com.relivus.generator.ValueGeneratorFactory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * 循环依赖 FK 为 NOT NULL 的集成测试。
 *
 * <p>team_a ↔ team_b 互相引用且外键列 NOT NULL：两阶段插入无法先置 NULL，
 * 引擎必须校验并抛出 {@code RELIVUS_CIRCULAR_FK_NOT_NULL}。
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CircularFkNotNullIT extends AbstractDatabaseIT {

    private final DataGenerationEngine engine = new DataGenerationEngine(new ValueGeneratorFactory(), INTROSPECTOR);

    @Test
    void notNullCircularFkRejectedOnMysql() throws Exception {
        setupCircular(mysqlDataSource(), true);
        assertThatThrownBy(() -> engine.execute(mysqlDataSource(), MYSQL_DIALECT,
                cfg(), null))
                .isInstanceOf(RelivusException.class)
                .hasFieldOrPropertyWithValue("code", ErrorCode.CIRCULAR_FK_NOT_NULL.getCode());
    }

    @Test
    void notNullCircularFkRejectedOnPostgres() throws Exception {
        setupCircular(pgDataSource(), false);
        assertThatThrownBy(() -> engine.execute(pgDataSource(), PG_DIALECT,
                cfg(), null))
                .isInstanceOf(RelivusException.class)
                .hasFieldOrPropertyWithValue("code", ErrorCode.CIRCULAR_FK_NOT_NULL.getCode());
    }

    private void setupCircular(javax.sql.DataSource ds, boolean mysql) throws Exception {
        execute(ds,
                "DROP TABLE IF EXISTS team_b",
                "DROP TABLE IF EXISTS team_a",
                "CREATE TABLE team_a (id " + (mysql ? "BIGINT NOT NULL AUTO_INCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY")
                        + " PRIMARY KEY, lead_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL)",
                "CREATE TABLE team_b (id " + (mysql ? "BIGINT NOT NULL AUTO_INCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY")
                        + " PRIMARY KEY, mid_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL)",
                "ALTER TABLE team_a ADD CONSTRAINT fk_a_lead FOREIGN KEY (lead_id) REFERENCES team_b(id)",
                "ALTER TABLE team_b ADD CONSTRAINT fk_b_mid FOREIGN KEY (mid_id) REFERENCES team_a(id)");
    }

    private static GenerationConfig cfg() {
        return new GenerationConfig(1L,
                List.of(new TableConfig("team_a", 3, Map.of()),
                        new TableConfig("team_b", 3, Map.of())),
                "UNIFORM", true, 100);
    }
}