package com.relivus.integration;

import com.relivus.dto.GenerationConfig;
import com.relivus.dto.GenerationConfig.TableConfig;
import com.relivus.generator.DataGenerationEngine;
import com.relivus.generator.GenerationRunResult;
import com.relivus.generator.ValueGeneratorFactory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 数据生成引擎集成测试（DOC-08 / DOC-03）。
 *
 * <p>双数据库真实执行：外键完整性、唯一无冲突、循环依赖可空成功。
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class GenerationEngineIT extends AbstractDatabaseIT {

    private final DataGenerationEngine engine = new DataGenerationEngine(new ValueGeneratorFactory(), INTROSPECTOR);

    @Test
    void generatesWithFkIntegrityOnMysql() throws Exception {
        setupTables(mysqlDataSource(), true);
        GenerationRunResult result = engine.execute(mysqlDataSource(), MYSQL_DIALECT,
                cfg(List.of(table("customers", 20), table("orders", 60))), null);

        assertThat(result.rowsByTable()).containsEntry("customers", 20L).containsEntry("orders", 60L);
        Long orphan = new JdbcTemplate(mysqlDataSource()).queryForObject(
                "SELECT COUNT(*) FROM orders o LEFT JOIN customers c ON o.customer_id = c.id"
                        + " WHERE c.id IS NULL", Long.class);
        assertThat(orphan).isZero();

        // 唯一约束无冲突：email 全部不同
        long distinct = new JdbcTemplate(mysqlDataSource()).queryForObject(
                "SELECT COUNT(DISTINCT email) FROM customers", Long.class);
        assertThat(distinct).isEqualTo(20L);
    }

    @Test
    void generatesWithFkIntegrityOnPostgres() throws Exception {
        setupTables(pgDataSource(), false);
        GenerationRunResult result = engine.execute(pgDataSource(), PG_DIALECT,
                cfg(List.of(table("customers", 15), table("orders", 45))), null);

        assertThat(result.rowsByTable()).containsEntry("customers", 15L).containsEntry("orders", 45L);
        Long orphan = new JdbcTemplate(pgDataSource()).queryForObject(
                "SELECT COUNT(*) FROM orders o LEFT JOIN customers c ON o.customer_id = c.id"
                        + " WHERE c.id IS NULL", Long.class);
        assertThat(orphan).isZero();
    }

    @Test
    void twoTableCycleSucceedsOnMysql() throws Exception {
        execute(mysqlDataSource(),
                "DROP TABLE IF EXISTS team_b",
                "DROP TABLE IF EXISTS team_a",
                "CREATE TABLE team_a (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " lead_id BIGINT NULL, name VARCHAR(64) NOT NULL)",
                "CREATE TABLE team_b (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " mid_id BIGINT NULL, name VARCHAR(64) NOT NULL)",
                "ALTER TABLE team_a ADD CONSTRAINT fk_a_lead FOREIGN KEY (lead_id) REFERENCES team_b(id)",
                "ALTER TABLE team_b ADD CONSTRAINT fk_b_mid FOREIGN KEY (mid_id) REFERENCES team_a(id)");

        GenerationRunResult result = engine.execute(mysqlDataSource(), MYSQL_DIALECT,
                cfg(List.of(table("team_a", 5), table("team_b", 5))), null);
        assertThat(result.rowsByTable()).containsEntry("team_a", 5L).containsEntry("team_b", 5L);
        Long nullFk = new JdbcTemplate(mysqlDataSource()).queryForObject(
                "SELECT COUNT(*) FROM team_a WHERE lead_id IS NULL", Long.class);
        assertThat(nullFk).isZero();
    }

    @Test
    void twoTableCycleSucceedsOnPostgres() throws Exception {
        execute(pgDataSource(),
                "DROP TABLE IF EXISTS team_b",
                "DROP TABLE IF EXISTS team_a",
                "CREATE TABLE team_a (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " lead_id BIGINT NULL, name VARCHAR(64) NOT NULL)",
                "CREATE TABLE team_b (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " mid_id BIGINT NULL, name VARCHAR(64) NOT NULL)",
                "ALTER TABLE team_a ADD CONSTRAINT fk_a_lead FOREIGN KEY (lead_id) REFERENCES team_b(id)",
                "ALTER TABLE team_b ADD CONSTRAINT fk_b_mid FOREIGN KEY (mid_id) REFERENCES team_a(id)");

        GenerationRunResult result = engine.execute(pgDataSource(), PG_DIALECT,
                cfg(List.of(table("team_a", 5), table("team_b", 5))), null);
        assertThat(result.rowsByTable()).containsEntry("team_a", 5L).containsEntry("team_b", 5L);
        Long nullFk = new JdbcTemplate(pgDataSource()).queryForObject(
                "SELECT COUNT(*) FROM team_a WHERE lead_id IS NULL", Long.class);
        assertThat(nullFk).isZero();
    }

    private void setupTables(javax.sql.DataSource ds, boolean mysql) throws Exception {
        String pk = mysql ? "BIGINT NOT NULL AUTO_INCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY";
        execute(ds,
                "DROP TABLE IF EXISTS orders",
                "DROP TABLE IF EXISTS customers",
                "CREATE TABLE customers (id " + pk + " PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL, email VARCHAR(128) NULL,"
                        + " CONSTRAINT uk_customers_email UNIQUE (email))",
                "CREATE TABLE orders (id " + pk + " PRIMARY KEY,"
                        + " customer_id BIGINT NOT NULL, total DECIMAL(10,2),"
                        + " CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id))");
    }

    private static GenerationConfig cfg(List<TableConfig> tables) {
        return new GenerationConfig(1L, tables, "UNIFORM", true, 500);
    }

    private static TableConfig table(String name, int rows) {
        // 不显式配置列：引擎按列名启发式/类型默认自动选择生成器（真实链路）
        return new TableConfig(name, rows, Map.of());
    }
}