package com.relivus.integration;

import com.relivus.config.RelivusProperties;
import com.relivus.dto.MaskingConfig;
import com.relivus.dto.MaskingTaskRequest;
import com.relivus.dto.MaskingTaskRequest.TableRule;
import com.relivus.dto.MaskingTaskRequest.TableRule.ColumnRule;
import com.relivus.masking.GlobalMaskingContext;
import com.relivus.masking.MaskingEngine;
import com.relivus.masking.MaskingRunResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 脱敏引擎跨表 JOIN 一致性集成测试。
 *
 * <p>orders.customer_name 与 customers.name 共享同一映射组：同原始值脱敏后
 * 仍保持一致，保证 JOIN 键在脱敏后仍可关联。
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class MaskingEngineIT extends AbstractDatabaseIT {

    private MaskingEngine newEngine(DataSource metaDs, String metaUrl) {
        RelivusProperties props = new RelivusProperties();
        props.getMeta().setUrl(metaUrl);
        byte[] key = new byte[32];
        for (int i = 0; i < key.length; i++) {
            key[i] = (byte) 9;
        }
        props.getMasking().setHmacKey(java.util.Base64.getEncoder().encodeToString(key));
        return new MaskingEngine(INTROSPECTOR, new GlobalMaskingContext(metaDs, props));
    }

    @Test
    void crossTableJoinKeyStaysConsistentOnMysql() throws Exception {
        DataSource ds = mysqlDataSource();
        execute(ds,
                "DROP TABLE IF EXISTS orders",
                "DROP TABLE IF EXISTS customers",
                "DROP TABLE IF EXISTS df_mask_mapping",
                "CREATE TABLE customers (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL)",
                "CREATE TABLE orders (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " customer_id BIGINT NOT NULL, customer_name VARCHAR(64) NOT NULL)",
                "CREATE TABLE df_mask_mapping (column_group VARCHAR(128), original_hash VARCHAR(64),"
                        + " masked_value VARCHAR(512), algorithm VARCHAR(32), key_version INT,"
                        + " UNIQUE KEY uk_group_hash (column_group, original_hash))");
        JdbcTemplate jdbc = new JdbcTemplate(ds);
        // 同一客户在两表出现同值（模拟跨表同名 JOIN 键）
        jdbc.update("INSERT INTO customers(name) VALUES ('张三'),('李四')");
        jdbc.update("INSERT INTO orders(customer_id, customer_name) VALUES (1,'张三'),(2,'李四')");
        // 全 custom 分组：同一映射组内同原始值脱敏一致
        MaskingTaskRequest request = new MaskingTaskRequest(1L,
                List.of(new TableRule("customers",
                                Map.of("name", new ColumnRule("fixed", Map.of("value", "MASK"), "customerGroup", null)), null),
                        new TableRule("orders",
                                Map.of("customer_name", new ColumnRule("fixed", Map.of("value", "MASK"), "customerGroup", null)), null)),
                null, null);
        MaskingEngine engine = newEngine(ds, dsMetaUrl(ds, true));
        MaskingRunResult result = engine.execute(ds, MYSQL_DIALECT, request, null);
        assertThat(result.rowsByTable()).containsEntry("customers", 2L).containsEntry("orders", 2L);

        List<String> names = jdbc.queryForList("SELECT name FROM customers ORDER BY id", String.class);
        assertThat(names).containsOnly("MASK");
        // 映射表按组+原始值幂等落库：两条不同原始值 → 2 条映射
        Long mappings = jdbc.queryForObject("SELECT COUNT(*) FROM df_mask_mapping", Long.class);
        assertThat(mappings).isEqualTo(2L);
    }

    @Test
    void crossTableJoinKeyStaysConsistentOnPostgres() throws Exception {
        DataSource ds = pgDataSource();
        execute(ds,
                "DROP TABLE IF EXISTS orders",
                "DROP TABLE IF EXISTS customers",
                "DROP TABLE IF EXISTS df_mask_mapping",
                "CREATE TABLE customers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL)",
                "CREATE TABLE orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " customer_id BIGINT NOT NULL, customer_name VARCHAR(64) NOT NULL)",
                "CREATE TABLE df_mask_mapping (column_group VARCHAR(128), original_hash VARCHAR(64),"
                        + " masked_value VARCHAR(512), algorithm VARCHAR(32), key_version INT,"
                        + " CONSTRAINT uk_group_hash UNIQUE (column_group, original_hash))");
        JdbcTemplate jdbc = new JdbcTemplate(ds);
        jdbc.update("INSERT INTO customers(name) VALUES ('张三'),('李四')");
        jdbc.update("INSERT INTO orders(customer_id, customer_name) VALUES (1,'张三'),(2,'李四')");
        MaskingTaskRequest request = new MaskingTaskRequest(1L,
                List.of(new TableRule("customers",
                                Map.of("name", new ColumnRule("fixed", Map.of("value", "MASK"), "customerGroup", null)), null),
                        new TableRule("orders",
                                Map.of("customer_name", new ColumnRule("fixed", Map.of("value", "MASK"), "customerGroup", null)), null)),
                null, null);
        MaskingEngine engine = newEngine(ds, dsMetaUrl(ds, false));
        MaskingRunResult result = engine.execute(ds, PG_DIALECT, request, null);
        assertThat(result.rowsByTable()).containsEntry("customers", 2L).containsEntry("orders", 2L);

        Long joinMatches = jdbc.queryForObject(
                "SELECT COUNT(*) FROM orders o JOIN customers c ON o.customer_name = c.name", Long.class);
        assertThat(joinMatches).isEqualTo(2L);
    }

    /** 元库即目标库（集成测试简化）：URL 前缀决定 MaskMappingRepository 方言。 */
    private String dsMetaUrl(javax.sql.DataSource ds, boolean mysql) {
        return mysql
                ? "jdbc:mysql://127.0.0.1:3306/relivus_meta"
                : "jdbc:postgresql://127.0.0.1:5432/relivus_meta";
    }

    /** 触发 unUsed 告警避免（保持 Record 完整性）。 */
    @SuppressWarnings("unused")
    private static MaskingConfig unusedConfig() {
        return MaskingConfig.of("fixed", "g");
    }
}