package com.relivus.integration;

import com.relivus.schema.model.ColumnMetadata;
import com.relivus.schema.model.TableMetadata;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.sql.Connection;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 双数据库内省集成测试（DOC-08 / DOC-02）。
 *
 * <p>在真实 MySQL / PostgreSQL 容器上验证：表、列、主键、外键、唯一索引、CHECK、
 * ENUM 的完整读取链路。
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SchemaIntrospectorIT extends AbstractDatabaseIT {

    @Test
    void introspectsMysqlSchema() throws Exception {
        execute(mysqlDataSource(),
                "DROP TABLE IF EXISTS orders",
                "DROP TABLE IF EXISTS customers",
                "DROP TABLE IF EXISTS customer_status",
                "CREATE TABLE customer_status (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " status ENUM('gold','silver') NOT NULL)",
                "CREATE TABLE customers ("
                        + " id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL,"
                        + " email VARCHAR(128) NULL,"
                        + " level VARCHAR(16) NULL CHECK (level IN ('gold','silver')),"
                        + " status_id BIGINT NULL,"
                        + " CONSTRAINT uk_customers_email UNIQUE (email),"
                        + " CONSTRAINT fk_customers_status FOREIGN KEY (status_id) REFERENCES customer_status(id))",
                "CREATE TABLE orders ("
                        + " id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
                        + " customer_id BIGINT NOT NULL,"
                        + " total DECIMAL(10,2),"
                        + " CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id))");

        List<TableMetadata> tables = introspect(mysqlDataSource().getConnection(), MYSQL_DIALECT);

        TableMetadata customers = tableByName(tables, "customers");
        assertThat(customers).isNotNull();
        assertThat(customers.primaryKey()).isEqualTo("id");
        assertThat(customers.column("id").autoIncrement()).isTrue();
        assertThat(customers.column("level").dataType()).containsIgnoringCase("VARCHAR");

        // 唯一索引
        assertThat(customers.uniqueIndexes())
                .anyMatch(ui -> ui.columns().contains("email"));

        // CHECK 约束
        assertThat(customers.checkConstraints()).isNotEmpty();

        // 外键
        TableMetadata orders = tableByName(tables, "orders");
        assertThat(orders).isNotNull();
        assertThat(orders.foreignKeys().stream().map(fk -> fk.refTable()))
                .contains("customers");

        // ENUM 列
        TableMetadata statusTable = tableByName(tables, "customer_status");
        assertThat(statusTable).isNotNull();
        ColumnMetadata status = statusTable.column("status");
        assertThat(status.isEnum()).isTrue();
        assertThat(status.enumValues()).contains("gold", "silver");
    }

    @Test
    void introspectsPostgresSchema() throws Exception {
        execute(pgDataSource(),
                "DROP TABLE IF EXISTS orders",
                "DROP TABLE IF EXISTS customers",
                "DROP TYPE IF EXISTS customer_status_enum",
                "CREATE TYPE customer_status_enum AS ENUM ('gold','silver')",
                "CREATE TABLE customers ("
                        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL,"
                        + " email VARCHAR(128) NULL,"
                        + " level VARCHAR(16) NULL CHECK (level IN ('gold','silver')),"
                        + " status customer_status_enum NULL,"
                        + " CONSTRAINT uk_customers_email UNIQUE (email))",
                "CREATE TABLE orders ("
                        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " customer_id BIGINT NOT NULL,"
                        + " total DECIMAL(10,2),"
                        + " CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id))");

        List<TableMetadata> tables = introspect(pgDataSource().getConnection(), PG_DIALECT);

        TableMetadata customers = tableByName(tables, "customers");
        assertThat(customers).isNotNull();
        assertThat(customers.primaryKey()).isEqualTo("id");

        assertThat(customers.uniqueIndexes())
                .anyMatch(ui -> ui.columns().contains("email"));

        assertThat(customers.checkConstraints()).isNotEmpty();

        TableMetadata orders = tableByName(tables, "orders");
        assertThat(orders).isNotNull();
        assertThat(orders.foreignKeys().stream().map(fk -> fk.refTable()))
                .contains("customers");

        // PG 原生 ENUM 类型列
        ColumnMetadata status = customers.column("status");
        assertThat(status).isNotNull();
        assertThat(status.enumValues()).contains("gold", "silver");
    }

    private List<TableMetadata> introspect(Connection connection, com.relivus.dialect.DatabaseDialect dialect) {
        try (connection) {
            return INTROSPECTOR.introspect(connection, dialect);
        } catch (Exception e) {
            throw new IllegalStateException("introspect failed", e);
        }
    }

    private TableMetadata tableByName(List<TableMetadata> tables, String name) {
        return tables.stream()
                .filter(t -> t.tableName().equalsIgnoreCase(name))
                .findFirst()
                .orElse(null);
    }
}