-- ============================================================
-- Relivus 初始化脚本（PostgreSQL 版）— 由数据库超级用户执行一次
-- 执行：psql -h 127.0.0.1 -U postgres -f init.sql
-- 说明：
--   1. 创建应用用户 relivus 与元库 relivus_meta；元库表结构由应用启动时
--      Flyway 自动迁移（db/migration/postgresql/V1__init.sql），此处不建表。
--   2. 创建演示目标库 relivus_demo（users/orders，含 ENUM / CHECK / UNIQUE /
--      外键，覆盖两种方言能力）；目标库由用户在 UI 中配置连接，Relivus 不迁移目标库。
--   3. 密码为占位值，部署前务必修改为强密码并同步到 /etc/relivus/relivus.env。
-- ============================================================

-- 应用用户（不存在才创建）
SELECT format('CREATE ROLE relivus LOGIN PASSWORD %L', 'change-me-strong')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'relivus')
\gexec

-- 元数据库（不存在才创建）
SELECT 'CREATE DATABASE relivus_meta OWNER relivus'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'relivus_meta')
\gexec

-- 演示目标库（不存在才创建）
SELECT 'CREATE DATABASE relivus_demo OWNER relivus'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'relivus_demo')
\gexec

\connect relivus_demo

-- ---------- 演示目标库结构（与本地联调库 relivus_demo 同构） ----------

CREATE TYPE public.order_status AS ENUM ('NEW', 'PAID', 'SHIPPED', 'DONE');
CREATE TYPE public.user_gender AS ENUM ('男', '女');

COMMENT ON TYPE public.order_status IS '订单状态：NEW/PAID/SHIPPED/DONE';
COMMENT ON TYPE public.user_gender IS '用户性别：男/女';

CREATE TABLE public.users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      character varying(255) NOT NULL,
    name       character varying(64) NOT NULL,
    age        integer NOT NULL,
    gender     public.user_gender NOT NULL,
    balance    numeric(18,2) NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_age_check CHECK ((age >= 18) AND (age <= 70)),
    CONSTRAINT users_balance_check CHECK ((balance >= (0)::numeric)),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX idx_users_name ON public.users (name);

COMMENT ON COLUMN public.users.email IS '登录邮箱，唯一，纯 ASCII 码（不含汉字）';
COMMENT ON COLUMN public.users.name IS '姓名（现代常用中文名，2~4 字）';
COMMENT ON COLUMN public.users.age IS '年龄，约束 18~70';
COMMENT ON COLUMN public.users.gender IS '性别：男/女';
COMMENT ON COLUMN public.users.balance IS '账户余额，保留 2 位小数，不允许为负';
COMMENT ON COLUMN public.users.created_at IS '创建时间（不超过当前时间）';

CREATE TABLE public.orders (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL,
    amount     numeric(10,2),
    status     public.order_status DEFAULT 'NEW'::public.order_status,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT orders_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id)
);